name: mpesa_sdk_dart
description: A Dart package for M-Pesa API (Mozambique). This package can be used in every dart frameworks as it's written in plain dart.
version: 1.0.0
author: Ergito Vilanculos <ergitorubildo@gmail.com>
repository: https://github.com/realrgt/mpesa_sdk_dart
homepage: https://github.com/realrgt/mpesa_sdk_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  pointycastle: ^1.0.2
  asn1lib: ^0.6.4
  http: ^0.12.1
  